version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crossed
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      PGHOST: db
      PGUSER: postgres
      PGPORT: 5432
      PGPASSWORD: postgres
      POSTGRES_DB: crossed
      SECRET_ACCESS_TOKEN: adfhadfhadfh2j51jk
      SECRET_KEY_PATH: "../src/config/secret-key"
    ports:
      - "3000:3000"
    command: ["yarn", "dev"]

volumes:
  postgres_data:
