name: CI - Backend

on:
  push:
    branches:
      - '**'
    paths:
      - 'backend/**'
  pull_request:
    branches:
      - '**'
    paths:
      - 'backend/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: yarn install
        working-directory: backend

      - name: Run tests
        run: yarn test:ci
        working-directory: backend
